### ISSUE TITLE
Support of backdrop-filter ?

### ISSUE THREAD

**Issue by cedriceberhardt** [iamvdo/pleeease-filters#10]
I don't test if it's possible with SVG or even with the ::before pseudo-element but what about the support of [backdrop-filter from Safari 9](https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW22) ?

**Comment by iamvdo** [comment]
Not really possible, I wrote here why: http://iamvdo.me/en/blog/css-element-function#faking-backdrop-filter
For now, only prefix is needed, and I made PR on Autoprefixer: https://github.com/postcss/autoprefixer-core/pull/65

**Comment by cedriceberhardt** [comment]
Sad. Thanks for the infos and nice for autoprefixer :+1:
