### ISSUE TITLE
Automatically add/remove filters based on browserslist?

### ISSUE THREAD

**Issue by ben-eb** [iamvdo/pleeease-filters#8]
Ref: https://github.com/cssnext/cssnext/issues/164#issuecomment-114912470. :smile:

**Comment by MoOx** [comment]
I think it's up to the user (in this case cssnext) to enable or disable this plugin. browserlist with caniuse usage should be reserved to plugins that handle several things (like autoprefixer or cssnext).

**Comment by iamvdo** [comment]
@MoOx Agree. Not worth it here.

**Comment by ben-eb** [comment]
Sorry, why not? This plugin is intended to provide a fallback for older browsers, and could get that data from other means.

For example - string option, parsed by browserslist; or array of browsers already from browserslist. So parsing happens only once, and then this module can decide whether it should be included or not. Both pleeease and cssnext (and any other consumers) get the detection 'for free'.

I don't see anything wrong with including a `browsers` option when your plugin specifically should target a subset of browsers, which users are likely going to want to configure.
