### ISSUE TITLE
Convert each filter to separate package

### ISSUE THREAD

**Issue by niksy** [iamvdo/pleeease-filters#9]
Following philosophy of "do one thing and do it well", maybe each filter should be it’s own package which is then required as dependancy for this project (e.g. `postcss-filter-grayscale`, `postcss-filter-sepia`, etc.). This would also benefit those who only want to process specific declarations.

**Comment by MoOx** [comment]
This package is kind of already deprecated since it was really usefull for Firefox < 35. So not sure if it's relevant.
But I guess since it's open source, you can copy/paste/explode this package & just respect the license right ? :)

**Comment by iamvdo** [comment]
@niksy: Separate each filters is over-engineering. It's like you ask for autoprefixer to split each prefixes in a specific package. 
Plus, @MoOx is right, this package is becoming useless over time

**Comment by niksy** [comment]
@iamvdo @MoOx noted :D Closing issue.
